SELECT CART_ID
FROM CART_PRODUCTS 
WHERE NAME IN ('Yogurt','Milk')
GROUP BY CART_ID 
HAVING COUNT(NAME) >= 2
   AND (SUM(PRICE) <> COUNT(NAME) * 2980) AND (SUM(PRICE) <> COUNT(NAME) * 1880)
ORDER BY CART_ID
   
   