SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE
     , PRODUCT_ID
     , USER_ID
     , SALES_AMOUNT AS SALES_AMOUNT
FROM ONLINE_SALE 
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

   
UNION ALL

SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE
     , PRODUCT_ID
     , NULL AS USER_ID
     , SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

ORDER BY SALES_DATE,PRODUCT_ID,USER_ID














# SELECT DATE_FORMAT(N.SALES_DATE, '%Y-%m-%d') AS SALES_DATE
#      , N.PRODUCT_ID
#      , N.USER_ID
#      , SUM(F.SALES_AMOUNT)
# FROM ONLINE_SALE N
# LEFT JOIN OFFLINE_SALE F ON N.PRODUCT_ID = F.PRODUCT_ID
# WHERE N.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
# GROUP BY N.SALES_DATE,N.PRODUCT_ID
# ORDER BY N.SALES_DATE


# SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") SALES_DATE,
#     PRODUCT_ID,
#     USER_ID,
#     SALES_AMOUNT
# FROM ONLINE_SALE
# WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

# UNION ALL

# SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") SALES_DATE,
#     PRODUCT_ID,
#     NULL AS USER_ID,
#     SALES_AMOUNT
# FROM OFFLINE_SALE 
# WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
    
# ORDER BY SALES_DATE , PRODUCT_ID , USER_ID