SELECT DISTINCT I.REST_ID
     , I.REST_NAME
     , I.FOOD_TYPE
     , I.FAVORITES
     , I.ADDRESS
     , ROUND((SELECT AVG(REVIEW_SCORE) AS SCORE
        FROM REST_REVIEW R2
        WHERE R2.REST_ID = I.REST_ID
        GROUP BY REST_ID),2) AS SCORE
FROM REST_INFO I
JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE LEFT(ADDRESS,2) = '서울'
ORDER BY SCORE DESC, I.FAVORITES DESC








# SELECT I.REST_ID
#      , I.REST_NAME
#      , I.FOOD_TYPE
#      , I.FAVORITES
#      , I.ADDRESS
#      , ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE
# FROM REST_INFO I
# INNER JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
# WHERE ADDRESS LIKE '서울%'
# GROUP BY I.REST_ID
# ORDER BY SCORE DESC, I.FAVORITES DESC