SET @HOUR = -1 ; # 변수 선언문
SELECT (@HOUR := @HOUR +1) AS HOUR # := 대입연산자, = 비교연산자
     , (SELECT COUNT(DATETIME) 
        FROM ANIMAL_OUTS 
        WHERE HOUR(DATETIME) = @HOUR) AS COUNT
FROM ANIMAL_OUTS
WHERE @HOUR < 23

