# SELECT M.MEMBER_NAME
#      , R.REVIEW_TEXT
#      , DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
# FROM REST_REVIEW R
# INNER JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
# WHERE M.MEMBER_NAME IN (SELECT MAX(M.MEMBER_NAME)
#                         FROM REST_REVIEW R
#                         INNER JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
#                         GROUP BY M.MEMBER_NAME
#                         ORDER BY COUNT(R.REVIEW_ID) DESC)
# GROUP BY M.MEMBER_NAME, R.REVIEW_TEXT
# ORDER BY R.REVIEW_DATE , R.REVIEW_TEXT

# SELECT M.MEMBER_NAME
# FROM REST_REVIEW R
# INNER JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
# GROUP BY M.MEMBER_NAME
# ORDER BY COUNT(R.REVIEW_ID) DESC

SELECT M.MEMBER_NAME
     , R.REVIEW_TEXT
     , DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
INNER JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
WHERE M.MEMBER_NAME IN (
    SELECT M.MEMBER_NAME
    FROM REST_REVIEW R
    INNER JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
    GROUP BY M.MEMBER_NAME
    HAVING COUNT(R.REVIEW_ID) = (
        SELECT MAX(ReviewCount)
        FROM (
            SELECT COUNT(R.REVIEW_ID) AS ReviewCount
            FROM REST_REVIEW R
            INNER JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
            GROUP BY M.MEMBER_NAME
        ) AS MaxReviewCount
    )
)
GROUP BY M.MEMBER_NAME, R.REVIEW_TEXT
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;                                           