SELECT INGREDIENT_TYPE
     , SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F
INNER JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE













-- 코드를 입력하세요
# SELECT I.INGREDIENT_TYPE,
# SUM(CASE 
#      WHEN I.INGREDIENT_TYPE = 'sugar_based' THEN F.TOTAL_ORDER
#      WHEN I.INGREDIENT_TYPE = 'fruit_based' THEN F.TOTAL_ORDER
#     END) AS TOTAL_ORDER
# FROM FIRST_HALF F
# LEFT JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
# GROUP BY I.INGREDIENT_TYPE
# ORDER BY TOTAL_ORDER