SELECT CATEGORY AS CATEGORY
     , SUM(SALES) AS TOTAL_SALES
FROM BOOK B
INNER JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY CATEGORY
ORDER BY CATEGORY











-- 코드를 입력하세요
# SELECT CATEGORY,
# SUM(CASE
#   WHEN CATEGORY = '경제' THEN SALES 
#   WHEN CATEGORY = '인문' THEN SALES
#   WHEN CATEGORY = '소설' THEN SALES
#   WHEN CATEGORY = '생활' THEN SALES
#   WHEN CATEGORY = '기술' THEN SALES
#  END) AS TOTAL_SALES
# FROM BOOK B
# LEFT JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
# WHERE LEFT(DATE_FORMAT(S.SALES_DATE, '%Y-%m-%d'), 7) = '2022-01'
# GROUP BY CATEGORY
# ORDER BY CATEGORY